home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

sportscenter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as OrderViews

urlpatterns = [
    path('', include('home.urls')), #path de bir şey yazmadan home çalıştırır
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('galeri/', views.galeri, name='galeri'),
    path('fiyatlar/', views.fiyatlar, name='fiyatlar'),
    path('join/', views.join_view, name='join_view'),
    path('login/', views.login_view, name='login_view'),
    path('category/<int:id>/<slug:slug>/', views.products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/',views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name="product_search_auto"),
    path('logout/', views.logout_view, name='logout_view'),
    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    path('sss/', views.sss, name='sss'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city','country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from home.models import Setting, UserProfile
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderProduct
from product.models import Category, Product


def index(request):
    #setting = Setting.objects.get(pk=1)
    return HttpResponse("Order App")

@login_required(login_url='/login') #check login
def addtocart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user #access user session information
    #****** ÜRÜN SEPETTE Mİ KONTROLÜ *******
    checkproduct=ShopCart.objects.filter(product_id=id) #ürün sepette mi?
    if checkproduct:
        control=1 #ürün sepette
    else:
        control=0 #ürün sepette değil

    if request.method == 'POST': #ÜRÜN DETAY SAYFASINDAN EKLE BUTONUNA BASINCA
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1: #ürün varsa güncelle
                data=ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save() #db kaydı
            else: #ürün yoksa ekle
                data=ShopCart() #model ile bağlantı
                data.user_id=current_user.id
                data.product_id=id
                data.quantity = form.cleaned_data['quantity']
                data.save() #db kaydı

        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count() #listedekileri sayar
        messages.success(request,"Ürün eklenmiştir. Sporla Kalın!")
        return HttpResponseRedirect(url)

    else: #ANASAYFADAN EKLE BUTONUNA BASINCA
        if control == 1:  # ürün varsa güncelle
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()  # db kaydı
        else:  # ürün yoksa ekle
            data = ShopCart() # model ile bağlantı
            data.user_id = current_user.id
            data.product_id = id
            data.quantity=1
            data.save() # db kaydı

        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # listedekileri sayar
        messages.success(request, "Ürün eklenmiştir. Sporla Kalın!")
        return HttpResponseRedirect(url)

    messages.warning(request,"Ürün kaydı yapılamamıştır.")
    return  HttpResponseRedirect(url)

@login_required(login_url='/login') #check login
def shopcart(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # listedekileri sayar

    total=0
    for rs in shopcart:
        total += rs.product.price * rs.quantity
    context={'setting': setting,
             'shopcart': shopcart,
             'category':category,
             'total': total,
             }
    return render(request,'shopcart_products.html',context)

@login_required(login_url='/login') # Check login
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    current_user=request.user  # Access User Session information
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()  # listedekileri sayar
    messages.success(request, "Seçtiğiniz spor sepetten silinmiştir.")
    return HttpResponseRedirect("/shopcart")

@login_required(login_url='/login')  # Check login
def orderproduct(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    product = Product.objects.all()
    current_user = request.user
    shopcart=ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total+= rs.product.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        if form.is_valid():
            #kredi kartı bilgilerini bankaya gönder onay gelirse dewamkee
            #<*><*><*><*>#
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total=total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(8).upper() #random kod üretir
            data.code = ordercode
            data.save()

            #move shopcart items to order products items
            shopcart=ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id #order id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                detail.price        = rs.product.price
                detail.amount       = rs.amount
                detail.save()
                #***** reduce quantity of sold product from amount of product
                product=Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()
                #****+++---*****

            ShopCart.objects.filter(user_id=current_user.id).delete() #Clear and Delete ShopCart
            request.session['cart_items']=0
            messages.success(request, "Üyeliğiniz başarıyla tamamlanmıştır. Sporla kalın! ")
            return render(request, 'Order_Completed.html', {'ordercode': ordercode,
                                                            'category': category,
                                                            'setting': setting})

        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct/")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'category': category,
               'shopcart':shopcart,
               'form': form,
               'total': total,
               'profile': profile,
               'product': product,
               'setting': setting,
               }
    return render(request, 'Order_Form.html', context)

order/templates/Order_Completed.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}Üyelik Fiyatları - {{ setting.title }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}


{% block content %}
    <!-- bradcam_area -->
    <div class="bradcam_area">
        <div class="single_bradcam  d-flex align-items-center bradcam_bg_2 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-9">
                        <div class="bradcam_text text-center">
                            <h3>KAYIT<BR>YAPILDI</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="big_offer_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="offter_text text-center">
                        <h3>Teşekkürler<br>{{ user }}</h3>
                        <h2 style="color: #cce5ff">SPOR MERKEZİMİZE KAYDINIZ TAMAMLANMIŞTIR.</h2>
                        <h2 STYLE="color: #cce5ff">ÜYE NUMARANIZ : {{ ordercode }}</h2>
                        <h2 STYLE="color: #cce5ff">SPORLA KALIN!</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

order/templates/Order_Form.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}Üyelik Fiyatları - {{ setting.title }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}


{% block content %}
    <!-- bradcam_area -->
    <div class="bradcam_area">
        <div class="single_bradcam  d-flex align-items-center bradcam_bg_2 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-9">
                        <div class="bradcam_text text-center">
                            <h3>SİPARİŞ<BR>FORMU</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="whole-wrap">
        <div class="container box_1170">
            <div class="section-top-border">
                <form action="" method="post">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="single-defination">
                                <h3 class="mb-30">Üyelik Detayları</h3>
                                {% csrf_token %}
                                <label for="id_city" style="color: #d01d33">Şehir:</label><br>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">İstanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">İzmir</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Karabük">Karabük</option>
                                </select>
                                <br><br><label for="id_first_name" style="color: #d01d33">İsim:</label><br>
                                <input type="text" name="first_name" value="{{ user.first_name }}" class="input" maxlength=" "><br>
                                <label for="id_last_name" style="color: #d01d33">Soyisim:</label><br>
                                <input type="text" name="last_name" value="{{ user.last_name }}" class="input" maxlength=" "><br>
                                <label for="id_address" style="color: #d01d33">Adres:</label><br>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength=" "><br>
                                <label for="id_phone" style="color: #d01d33">Telefon:</label><br>
                                <input type="text" name="phone" value="{{ profile.phone }}" class="input" maxlength=" "><br>
                                <label for="id_firt_name" style="color: #d01d33">Ülke:</label><br>
                                <input type="text" name="country"class="input" id="id_country" value="{{ profile.country }}" maxlength=" "><br>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="single-defination">
                                <div class="blog_left_sidebar">
                                    <h3 class="mb-30">Ödeme Detayları</h3>
                                    <label for="id_first_name" style="color: #d01d33">Toplam Ücret: </label><br>
                                    <input type="text" name="total" class="input" readonly value="${{ total }}"><br>
                                    <label for="id_first_name" style="color: #d01d33">Kart Sahibinin Adı</label><br>
                                    <input type="text" name="holder" class="input" value=""><br>
                                    <label for="id_first_name" style="color: #d01d33">Kredi Kartı Numarası</label><br>
                                    <input type="text" name="number" class="input" value=""><br>
                                    <label for="id_first_name" style="color: #d01d33">Son Kullanma Tarihi</label><br>
                                    <input type="text" name="ecpdate" class="input" value="mm/yy"><br>
                                    <label for="id_first_name" style="color: #d01d33">CVV</label><br>
                                    <input type="text" name="secnumber" class="input" value=""><br><br>
                                    <div class="controls">
                                        <button type="submit" class="defaultBtn" style="color: #d01d33; background: mediumaquamarine">Kaydı Tamamla</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
						<div class="single-defination">
							<h4 class="mb-30">Teşekkürler! Sayın {{ user }}</h4>
							<p>
                                Şehrimizin önde gelen spor kompleksi olan EE|SporCenter'ı tercih ettiğiniz
                                için çok teşekkür ederiz.<br>
                                Spor merkezimiz haftanın 7 günü açıktır.
                                Pazartesiden Cumartesiye : 08.00 - 22.00
                                Pazar Günleri : 10.00 - 17. 00 saatleri arasında hizmetinizdeyiz.
                            </p>
						</div>
					</div>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

order/templates/shopcart_products.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}Üye Ürün Satış - {{ setting.title }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'>
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}


{% block content %}
    <!-- bradcam_area -->

    <div class="bradcam_area">
        <div class="single_bradcam  d-flex align-items-center bradcam_bg_2 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-xl-9">
                        <div class="bradcam_text text-center">
                            <h3>SEPET</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- bradcam_area end -->
    <!-- Start Align Area -->
    <div class="whole-wrap">
        <div class="container box_1170">
            <div class="section-top-border">
                <h3 class="mb-30">Kayıt İçin Eklenen Ürünler</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="progress-table-wrap">
                    <div class="progress-table">

                        <div class="table-head">
                            <div class="visit"><CENTER>SPOR</CENTER></div>
                            <div class="visit"><CENTER>ALINAN SPOR</CENTER></div>
                            <div class="visit"><CENTER>ÜCRET</CENTER></div>
                            <div class="visit"><CENTER>KİŞİ SAYISI</CENTER></div>
                            <div class="visit"><CENTER>TOPLAM</CENTER></div>
                            <div class="visit"><CENTER>KALDIR</CENTER></div>
                        </div>
                        {% for rs in shopcart %}
                            <div class="table-row">
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<img src="{{ rs.product.image.url }}" border="1" width="64px" height="64px"></div>
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ rs.product }}</div>
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ rs.product.price }}</div>
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ rs.quantity }}</div>
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;{{ rs.amount }}</div>
                                <div class="visit">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Emin misiniz?')">Sil</a></div>
                            </div>
                        {% endfor %}
                        <center>
                            <table border="2" bgcolor="#66cdaa" align="right">
                                <tr>
                                    <td width="150"><center>Toplam Ücret</center></td>
                                    <td width="150"><center>${{ total }}</center></td>
                                </tr>
                                <tr>
                                    <td width="150"><center>Üyelik Ücreti</center></td>
                                    <td width="150"><center>$0.0</center></td>
                                </tr>
                            </table>
                        </center>

                    </div>

                </div>
                <div class="controls" align="right">
                    <button type="submit" class="btn block" style="background: mediumaquamarine"><a href="/order/orderproduct">Üyelikleri Satın Al.</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- big_offer_area end  -->

{% endblock %}